[workspace]
members = [
  "swe-readline",
  "features/shell/engine",
  "features/shell/host",
  "features/shell/readline",
  "features/ai",
  "features/test",
]
default-members = ["features/shell/host"]
resolver = "2"

[workspace.dependencies]
swe-readline = { path = "swe-readline" }

[profile.release]
opt-level = "s"
lto = true
strip = true
