[workspace]
members = [
  "features/shell/engine",
  "features/shell/host",
  "features/shell/readline",
  "features/ai",
]
default-members = ["features/shell/host"]
resolver = "2"

[profile.release]
opt-level = "s"
lto = true
strip = true
